deploy:
  provider: heroku
  api_key: 766421a7-a7c9-4fab-9959-dcc395470440
    secure: aRYEA7YYkK0IndeOdFb+4uZMTFRMcAlGP6jbwdIez7lgYxP42mGk29fxcnMx2Oa54HrkAJvZEfLTLX3eL5lw0AlRpdTNSNGIcRVUpNNNYWTHJban4v7XMdl9HtsEHcTirC84nTSviuhkfBKSEUtzRl3c6YvbKF2+vTTlMwNCzniCcfj6rmZWN9dr/dSmOKrocBxvXLv/5e4WwQ9xcQcI4wQNPYoIpzc0RrQxcwSUO/v+SGtXuZXCQiFUhO9FFRRS3Iw61efLrCljX0EaTDo4wYbvXE85NbY8g0WSHdWSVh+cbxDd0JKOcawgY7dJBfz5SD1Ib6p78fxNV2WOsdEjszM64j55FNxGCfFmqWRAwMxFx+TbkoWAABy2zdjblM4Sivx/27vCyvdy5MYIkpMqf84t1gRPBxIYC4hQU3eHPlONsMg4Ie21MUBDKu1O3cMUVOCuU38uWL6QrR4/QOMCPlqOtDkpWGxeNiyG+JzQE/qQZcv6wfiR3+4lyk74JZrI8mjvEXTnkFs//1HrLHWIOfEqL+vUEjtZyDsfBz1CEMNtGPyipLJr/KZUg3TJSRW7UIwYvqmKv3Km1WgxIZTEXdAEEqMdaXZq38e5z0a3pK4/AqKsNp0lShp9nMk48nglE1/16U1bJj9Zq0EnTKEx4Dl+O6t6B3oFb+ogTHqpYg0=
  app: polar-garden-22411
  on:
    repo: apinango92/Tarea2
